name: Deploy Container App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Container App
        uses: azure/cli@v1
        with:
          azcliversion: 2.56.0
          inlineScript: |
            # Replace with your resource group and container app name
            RESOURCE_GROUP="brainhop-backend-dev"
            CONTAINER_APP_NAME="brainhop-backend-ca-dev"
            IMAGE="ghcr.io/cycrqr-max/brainhop-backend:latest"

            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $IMAGE